default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: postgres

development:
  <<: *default
  database: graphql_api_development

test:
  <<: *default
  database: graphql_api_test

production:
  <<: *default
  database: graphql_api_production
  username: graphql_api
  password: <%= ENV['GRAPHQL_API_DATABASE_PASSWORD'] %>
